using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using CowboyCafe.Data;

namespace Website.Pages
{
    public class IndexModel : PageModel
    {
        /// <summary>
        /// autogenerated code
        /// </summary>
        private readonly ILogger<IndexModel> _logger;
        /// <summary>
        /// autogenerated code
        /// </summary>
        /// <param name="logger"></param>
        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        /// <summary>
        /// The items to display on the index page 
        /// </summary>
        public IEnumerable<IOrderItem> Items { get; protected set; }

        /// <summary>
        /// The current search terms 
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public string SearchTerms { get; set; } = "";

        /// <summary>
        /// The minimum calories
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public int? CalorieMin { get; set; }

        /// <summary>
        /// The maximum calories
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public int? CalorieMax { get; set; }

        /// <summary>
        /// The minimum Price
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public double? PriceMin { get; set; }

        /// <summary>
        /// The maximum Price
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public double? PriceMax { get; set; }

        /// <summary>
        /// The filtered menu categories
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public string[] Categories { get; set; }

        /// <summary>
        /// On get method to make the search work
        /// </summary>
        public void OnGet()
        {
            

            Items = Menu.Search(SearchTerms);
            Items = Menu.FilterByCalories(Items, CalorieMin, CalorieMax);
            Items = Menu.FilterByPrice(Items, PriceMin, PriceMax);
            Items = Menu.FilterByCategory(Items, Categories);
        }

        
    }
}
